# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bidirectional.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bidirectional.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62idirectional.proto\x12\x04grpc\"\xa6\x01\n\tEntryMeta\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x1d\n\x04type\x18\x02 \x01(\x0e\x32\x0f.grpc.EntryType\x12\r\n\x05peers\x18\x03 \x03(\t\x12\x10\n\x08\x64\x61ta_len\x18\x04 \x01(\x03\x12\x11\n\told_peers\x18\x05 \x03(\t\x12\x10\n\x08\x63hecksum\x18\x06 \x01(\x03\x12\x10\n\x08learners\x18\x07 \x03(\t\x12\x14\n\x0cold_learners\x18\x08 \x03(\t\"4\n\rErrorResponse\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"\x88\x01\n\x13PullLogEntryRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x0f\n\x07peer_id\x18\x03 \x01(\t\x12\x0c\n\x04term\x18\x04 \x01(\x03\x12\x15\n\rprev_log_term\x18\x05 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x06 \x01(\x03\"\xc2\x01\n\x14PullLogEntryResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12 \n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x0f.grpc.EntryMeta\x12\x17\n\x0f\x63ommitted_index\x18\x05 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12*\n\rerrorResponse\x18\x63 \x01(\x0b\x32\x13.grpc.ErrorResponse*l\n\tEntryType\x12\x16\n\x12\x45NTRY_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10\x45NTRY_TYPE_NO_OP\x10\x01\x12\x13\n\x0f\x45NTRY_TYPE_DATA\x10\x02\x12\x1c\n\x18\x45NTRY_TYPE_CONFIGURATION\x10\x03*\x97\x01\n\tErrorType\x12\x13\n\x0f\x45RROR_TYPE_NONE\x10\x00\x12\x12\n\x0e\x45RROR_TYPE_LOG\x10\x01\x12\x15\n\x11\x45RROR_TYPE_STABLE\x10\x02\x12\x17\n\x13\x45RROR_TYPE_SNAPSHOT\x10\x03\x12\x1c\n\x18\x45RROR_TYPE_STATE_MACHINE\x10\x04\x12\x13\n\x0f\x45RROR_TYPE_META\x10\x05\x32X\n\rSimpleService\x12G\n\x0ePullLogEntries\x12\x19.grpc.PullLogEntryRequest\x1a\x1a.grpc.PullLogEntryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidirectional_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYTYPE']._serialized_start=588
  _globals['_ENTRYTYPE']._serialized_end=696
  _globals['_ERRORTYPE']._serialized_start=699
  _globals['_ERRORTYPE']._serialized_end=850
  _globals['_ENTRYMETA']._serialized_start=30
  _globals['_ENTRYMETA']._serialized_end=196
  _globals['_ERRORRESPONSE']._serialized_start=198
  _globals['_ERRORRESPONSE']._serialized_end=250
  _globals['_PULLLOGENTRYREQUEST']._serialized_start=253
  _globals['_PULLLOGENTRYREQUEST']._serialized_end=389
  _globals['_PULLLOGENTRYRESPONSE']._serialized_start=392
  _globals['_PULLLOGENTRYRESPONSE']._serialized_end=586
  _globals['_SIMPLESERVICE']._serialized_start=852
  _globals['_SIMPLESERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
